class FishyWheelz
  attr_accessor :fish, :adjectives, :products, :payment

  def initialize
    @fish = ["mackerel", "kipper", "sardine", "tuna", "salmon", "pilchard", "herring", "oyster", "roe", "cod", "bass", "shark", "waterdweller", "tadpole", "fish or non-fish", "crustacean", "xmas crab", "chicken of the sea", "leech", "froggy boy", "guppy", "fish finger", "goldfish", "carp", "catfish", "bream", "pike", "bluegill", "eel", "chub", "turbot", "blobfish", "pollack", "urchin", "seaweed", "boot", "tin can", "freaky lamp fish", "L O N G F I S H B O Y E", "octupus", "squiddy legs", "squiddy ink", "deep trench squiddy knees", "garbage", "jelyfish", "anchovy", "lungfish", "chub", "eeel", "electric ray", "hammerhead", "lefteye flounder", "mahi-mahi", "sunfish", "seehorse"]
    @adjectives = ["fascinating", "oily", "green", "blue", "yellow", "pungent", "pink", "greasy", "slimy", "mushed", "musky", "damp", "steamy", "steamed", "squishy", "KENNY LOGGed", "briney", "pickled", "boiled", "stewed", "baked", "fried", "poached", "microwaved", "cheesey", "hot-cheesey", "luke-warm", "tepid", "clammy", "sweaty", "sweet", "sour", "milky", "savoury", "flamin' hot", "spicy", "muddy", "smooth", "spikey", "hairy", "fuzzy", "viscous", "scaley", "artisanal", "humourously-shaped"]
    @products = ["canoe", "jacket", "deodorant", "paddle", "napkin", "soup", "shampoo", "notebook", "pistachios", "body lotion", "coasters", "jug", "wallpaper", "paint", "windmill", "windchime", "treadmill", "lounge pants", "graphic tee", "bouquet", "o de toilett", "toast", "butter", "wetabix", "gameboi", "paperweight", "table cloth", "meatballs", "tic toc clock", "prosthetic nose", "tanning lotion", "sense of inner peace", "hair gel", "digital goods and services", "peanuts", "nut butter", "protein shake", "tagine", "tea bags", "cheese balls", "cheese puffs", "wotsits", "cheesey footballs", "body butter", "foam", "burrito", "gravy boat", "lenovo thinkpad L470", "shiny shiny shoes", "mug", "codpiece", "500 page c++ manual", "syrup"]
    @payment = ["silver dollars", "pistachio shells", "click clacks", "daddy's smiles", "jingle jangles", "cents", "watermellas", "shillins", "roubles", "pesos", "rupees", "credits", "fun bux", "dollar pounds"]
  end

  def fish_me
    ["#{@adjectives.sample.upcase} #{@fish.sample} #{@products.sample} is on s ale now for just #{rand(11) + 2} #{@payment.sample}", "#{@fish.sample.upcase} #{@products.sample}? We got those!!! They're #{@adjectives.sample}!!! give me  #{rand(11) + 2} #{@payment.sample} and it is yours now my friend", "#{@products.sample.upcase}?!?!?!! but #{@fish.sample} flavour?? It's true and it's #{rand(11) + 2} #{@payment.sample} amd it's #{@adjectives.sample}", "#{rand(11) + 2} #{@payment.sample} 4 a #{@adjectives.sample} #{@adjectives.sample} m u l t i p a ck of #{rand(21) + 2} #{@products.sample}!!!!!!", "#{@adjectives.sample.upcase} HOT DEAL! Grab all ya #{@payment.sample}s and jingle on down for CHEEP #{@adjectives.sample} #{@products.sample}!1!!", "YOu want #{@adjectives.sample} #{@products.sample} for your #{rand(11) + 2} #{@payment.sample}?? NO??? how about #{@adjectives.sample.upcase} #{@fish.sample}??????"].sample
  end

end
